[project]
name = "day2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "adityarpandey", email = "aditya.119540@stu.upes.ac.in" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
day2 = "day2:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
